In [1]:
import mysql.connector as sql
import pandas as pd 
import numpy as np 
import advanced_statlines as stat

In [5]:
lahmans = sql.connect(user='root', passwd='wassup01L', db='lahmansbaseballdb')

NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported

In [2]:
pd.options.display.max_columns = None

In [3]:
batting = pd.read_csv('ari2001_batting.csv')
batting.head()

,playerID,nameFirst,nameLast,ID,playerID.1,yearID,stint,teamID,team_ID,lgID,G,G_batting,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,anderbr02,Brian,Anderson,80676,anderbr02,2001,1,ARI,2357,NL,33,NaN,37,1,5,1,1,0,2,0,0,0,9,0,0,0,0,2
1,barajro01,Rod,Barajas,80708,barajro01,2001,1,ARI,2357,NL,51,NaN,106,9,17,3,0,3,9,0,0,4,26,0,0,0,0,0
2,batismi01,Miguel,Batista,80716,batismi01,2001,1,ARI,2357,NL,48,NaN,32,2,2,0,0,0,0,0,0,2,17,0,0,2,0,0
3,bautida01,Danny,Bautista,80720,bautida01,2001,1,ARI,2357,NL,100,NaN,222,26,67,11,2,5,26,3,2,14,31,1,1,2,0,7
4,bellja01,Jay,Bell,80731,bellja01,2001,1,ARI,2357,NL,129,NaN,428,59,106,24,1,13,46,0,1,65,79,3,4,8,4,9

In [4]:
batting_formatted = stat.format_df(batting)
display(batting_formatted)

,playerID,nameFirst,nameLast,ID,playerID.1,yearID,stint,teamID,team_ID,lgID,G,G_batting,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,AVG
0,anderbr02,Brian,Anderson,80676,anderbr02,2001,1,ARI,2357,NL,33,NaN,37,1,5,1,1,0,2,0,0,0,9,0,0,0,0,2,37,0.135135,0.135135
1,barajro01,Rod,Barajas,80708,barajro01,2001,1,ARI,2357,NL,51,NaN,106,9,17,3,0,3,9,0,0,4,26,0,0,0,0,0,110,0.190909,0.160377
2,batismi01,Miguel,Batista,80716,batismi01,2001,1,ARI,2357,NL,48,NaN,32,2,2,0,0,0,0,0,0,2,17,0,0,2,0,0,36,0.111111,0.062500
3,bautida01,Danny,Bautista,80720,bautida01,2001,1,ARI,2357,NL,100,NaN,222,26,67,11,2,5,26,3,2,14,31,1,1,2,0,7,239,0.343096,0.301802
4,bellja01,Jay,Bell,80731,bellja01,2001,1,ARI,2357,NL,129,NaN,428,59,106,24,1,13,46,0,1,65,79,3,4,8,4,9,509,0.343811,0.247664
5,bierbni01,Nick,Bierbrodt,80754,bierbni01,2001,1,ARI,2357,NL,6,NaN,6,3,4,1,0,0,0,0,0,2,0,0,0,2,0,0,10,0.600000,0.666667
6,brohatr01,Troy,Brohawn,80794,brohatr01,2001,1,ARI,2357,NL,59,NaN,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.000000,0.000000
7,chrisry01,Ryan,Christenson,80864,chrisry01,2001,2,ARI,2357,NL,19,NaN,4,3,1,1,0,0,1,1,0,1,1,0,0,0,0,0,5,0.400000,0.250000
8,cintral01,Alex,Cintron,80866,cintral01,2001,1,ARI,2357,NL,8,NaN,7,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,7,0.285714,0.285714
9,colbrgr01,Greg,Colbrunn,80879,colbrgr01,2001,1,ARI,2357,NL,59,NaN,97,12,28,8,0,4,18,0,0,9,14,0,4,0,0,5,110,0.372727,0.288660
10,contija01,Jason,Conti,80886,contija01,2001,1,ARI,2357,NL,5,NaN,4,1,1,0,0,0,0,0,0,1,2,0,0,0,0,0,5,0.400000,0.250000
11,counscr01,Craig,Counsell,80901,counscr01,2001,1,ARI,2357,NL,141,NaN,458,76,126,22,3,4,38,6,8,61,76,3,2,6,6,9,533,0.354597,0.275109
12,cummimi01,Midre,Cummings,80920,cummimi01,2001,1,ARI,2357,NL,20,NaN,20,1,6,1,0,0,1,0,0,0,4,0,0,0,1,2,21,0.285714,0.300000
13,custja01,Jack,Cust,80923,custja01,2001,1,ARI,2357,NL,3,NaN,2,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,3,0.666667,0.500000
14,delluda01,David,Dellucci,80944,delluda01,2001,1,ARI,2357,NL,115,NaN,217,28,60,10,2,10,40,2,1,22,52,4,2,0,0,2,241,0.348548,0.276498
15,difelmi01,Mike,Difelice,80955,difelmi01,2001,2,ARI,2357,NL,12,NaN,21,1,1,0,0,0,1,0,0,0,10,0,1,1,0,0,23,0.086957,0.047619
16,durazer01,Erubiel,Durazo,80973,durazer01,2001,1,ARI,2357,NL,92,NaN,175,34,47,11,0,12,38,0,0,28,49,1,2,0,2,1,207,0.371981,0.268571
17,ellisro02,Robert,Ellis,80988,ellisro02,2001,1,ARI,2357,NL,19,NaN,26,2,4,0,0,0,1,0,0,1,12,0,0,1,0,0,28,0.178571,0.153846
18,finlest01,Steve,Finley,81027,finlest01,2001,1,ARI,2357,NL,140,NaN,495,66,136,27,4,14,73,11,7,47,67,9,1,2,3,8,548,0.335766,0.274747
19,gonzalu01,Luis,Gonzalez,81096,gonzalu01,2001,1,ARI,2357,NL,162,NaN,609,128,198,36,7,57,142,1,1,100,83,24,14,0,5,14,728,0.428571,0.325123
20,gracema01,Mark,Grace,81101,gracema01,2001,1,ARI,2357,NL,145,NaN,476,66,142,31,2,15,78,1,0,67,36,6,4,1,5,7,553,0.385172,0.298319
21,guzmage01,Geraldo,Guzman,81126,guzmage01,2001,1,ARI,2357,NL,4,NaN,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.000000,0.000000
22,huckake01,Ken,Huckaby,81194,huckake01,2001,1,ARI,2357,NL,1,NaN,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.000000,0.000000
23,johnsra05,Randy,Johnson,81236,johnsra05,2001,1,ARI,2357,NL,35,NaN,80,2,8,0,0,0,2,0,0,3,38,0,1,7,0,3,91,0.131868,0.100000
24,kimby01,Byung-Hyun,Kim,81265,kimby01,2001,1,ARI,2357,NL,78,NaN,6,0,1,0,0,0,2,0,0,0,2,0,0,0,0,0,6,0.166667,0.166667
25,knotter01,Eric,Knott,81276,knotter01,2001,1,ARI,2357,NL,3,NaN,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.000000,0.000000
26,koplomi01,Mike,Koplove,81283,koplomi01,2001,1,ARI,2357,NL,9,NaN,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.000000,0.000000
27,lopezal02,Albie,Lopez,81339,lopezal02,2001,2,ARI,2357,NL,13,NaN,24,0,1,0,0,0,0,0,0,2,10,0,1,2,0,1,29,0.137931,0.041667
28,mantema01,Matt,Mantei,81371,mantema01,2001,1,ARI,2357,NL,8,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
29,milleda02,Damian,Miller,81443,milleda02,2001,1,ARI,2357,NL,123,NaN,380,45,103,19,0,13,47,0,1,35,80,9,4,4,2,9,425,0.334118,0.271053
30,moellch01,Chad,Moeller,81457,moellch01,2001,1,ARI,2357,NL,25,NaN,56,8,13,0,1,1,2,0,0,6,12,1,0,1,0,2,63,0.301587,0.232143
31,mohlemi01,Mike,Mohler,81458,mohlemi01,2001,1,ARI,2357,NL,13,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
32,morgami01,Mike,Morgan,81468,morgami01,2001,1,ARI,2357,NL,31,NaN,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1.000000,NaN
33,overbly01,Lyle,Overbay,81546,overbly01,2001,1,ARI,2357,NL,2,NaN,2,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,2,0.500000,0.500000
34,prinzbr01,Bret,Prinz,81621,prinzbr01,2001,1,ARI,2357,NL,46,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
35,reynoar02,Armando,Reynoso,81662,reynoar02,2001,1,ARI,2357,NL,9,NaN,10,0,1,1,0,0,2,0,0,0,3,0,0,3,0,0,13,0.076923,0.100000
36,ryanro02,Rob,Ryan,81710,ryanro02,2001,1,ARI,2357,NL,1,NaN,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.000000,0.000000
37,sabeler01,Erik,Sabel,81713,sabeler01,2001,1,ARI,2357,NL,42,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
38,sandere02,Reggie,Sanders,81726,sandere02,2001,1,ARI,2357,NL,126,NaN,441,84,116,21,3,33,90,14,10,46,126,7,5,1,3,2,496,0.336694,0.263039
39,schilcu01,Curt,Schilling,81739,schilcu01,2001,1,ARI,2357,NL,35,NaN,83,4,11,1,0,0,1,0,0,1,28,0,0,14,0,0,98,0.122449,0.132530
40,sosaju01,Juan,Sosa,81786,sosaju01,2001,1,ARI,2357,NL,2,NaN,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0.000000,0.000000
41,spiveju01,Junior,Spivey,81794,spiveju01,2001,1,ARI,2357,NL,72,NaN,163,33,42,6,3,5,21,3,0,23,47,0,2,6,1,3,195,0.343590,0.257669
42,sprinru01,Russ,Springer,81798,sprinru01,2001,1,ARI,2357,NL,18,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
43,swindgr01,Greg,Swindell,81824,swindgr01,2001,1,ARI,2357,NL,64,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
44,willima04,Matt,Williams,81939,willima04,2001,1,ARI,2357,NL,106,NaN,408,58,112,30,0,16,65,1,0,22,70,3,3,0,3,15,436,0.314220,0.274510
45,wittbo01,Bobby,Witt,81961,wittbo01,2001,1,ARI,2357,NL,14,NaN,12,0,3,0,0,0,0,0,0,0,7,0,0,1,0,0,13,0.230769,0.250000
46,womacto01,Tony,Womack,81966,womacto01,2001,1,ARI,2357,NL,125,NaN,481,66,128,19,5,3,30,28,7,23,54,2,6,7,1,4,518,0.303089,0.266112