In [1]:
import mysql.connector as sql
import pandas as pd 
import numpy as np 
import advanced_statlines as stat

In [2]:
lahmans = sql.connect(user='root', passwd='wassup01L', db='lahmansbaseballdb')

In [3]:
pd.options.display.max_columns = None

In [4]:
batting = pd.read_csv('ari2001_batting.csv')
batting.head()

,playerID,nameFirst,nameLast,ID,playerID.1,yearID,stint,teamID,team_ID,lgID,G,G_batting,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,anderbr02,Brian,Anderson,80676,anderbr02,2001,1,ARI,2357,NL,33,NaN,37,1,5,1,1,0,2,0,0,0,9,0,0,0,0,2
1,barajro01,Rod,Barajas,80708,barajro01,2001,1,ARI,2357,NL,51,NaN,106,9,17,3,0,3,9,0,0,4,26,0,0,0,0,0
2,batismi01,Miguel,Batista,80716,batismi01,2001,1,ARI,2357,NL,48,NaN,32,2,2,0,0,0,0,0,0,2,17,0,0,2,0,0
3,bautida01,Danny,Bautista,80720,bautida01,2001,1,ARI,2357,NL,100,NaN,222,26,67,11,2,5,26,3,2,14,31,1,1,2,0,7
4,bellja01,Jay,Bell,80731,bellja01,2001,1,ARI,2357,NL,129,NaN,428,59,106,24,1,13,46,0,1,65,79,3,4,8,4,9

In [5]:
stat.format_df(batting)
batting.head()

,playerID,nameFirst,nameLast,ID,playerID.1,yearID,stint,teamID,team_ID,lgID,G,G_batting,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,AVG
0,anderbr02,Brian,Anderson,80676,anderbr02,2001,1,ARI,2357,NL,33,NaN,37,1,5,1,1,0,2,0,0,0,9,0,0,0,0,2,37,0.135135,0.135135
1,barajro01,Rod,Barajas,80708,barajro01,2001,1,ARI,2357,NL,51,NaN,106,9,17,3,0,3,9,0,0,4,26,0,0,0,0,0,110,0.190909,0.160377
2,batismi01,Miguel,Batista,80716,batismi01,2001,1,ARI,2357,NL,48,NaN,32,2,2,0,0,0,0,0,0,2,17,0,0,2,0,0,36,0.111111,0.062500
3,bautida01,Danny,Bautista,80720,bautida01,2001,1,ARI,2357,NL,100,NaN,222,26,67,11,2,5,26,3,2,14,31,1,1,2,0,7,239,0.343096,0.301802
4,bellja01,Jay,Bell,80731,bellja01,2001,1,ARI,2357,NL,129,NaN,428,59,106,24,1,13,46,0,1,65,79,3,4,8,4,9,509,0.343811,0.247664